### ISSUE TITLE
nesting hono routes returns undefined error

### ISSUE THREAD

**Issue by TheDanBlanco** [cloudflare/chanfana#179]
### Issue
using a `route` call on a `fromHono` chanfana proxy object returns `TypeError: Cannot read properties of undefined (reading 'basePath')`

### Minimal reproduction code

```ts
import { fromHono } from "chanfana";
import { type Context, Hono } from "hono";

const app = new Hono();

const parent = fromHono(app);

const nested = new Hono();
nested.get("/", (c) => c.text("hello, world"));

const child = fromHono(nested);

parent.route("/nested", child);

export default parent;
```

### Expected behavior
nesting chanfana proxies in a `route` function should produce the same results as when done in hono - that is, it should group the routes together as sub-routes

### Additional Info
Chanfana version: 2.0.4

Relevant stack trace
```
TypeError: Cannot read properties of undefined (reading 'basePath')
    at route (/Users/db/dev/cloudflare/simple/node_modules/hono/dist/cjs/hono-base.js:111:25)
    at Proxy.<anonymous> (/Users/db/dev/cloudflare/simple/node_modules/chanfana/dist/index.js:763:50)
```

the proxy referred to at the trace is located [here](https://github.com/cloudflare/chanfana/blob/main/src/adapters/hono.ts#L20), and the route call in hono is located [here](https://github.com/honojs/hono/blob/main/src/hono-base.ts#L207).

there's also currently no documentation in chanfana on how to group hono routes together, only ittyrouter.

**Comment by G4brym** [comment]
Hey @TheDanBlanco sorry about that, this issue has been known internally since the release of 2.0.0
I just didn't have time yet to go around fixing that
But this is a top priority for the next version, hopefully coming up soon, i will keep posting updates here

**Comment by omonk** [comment]
@G4brym - is there any update here? Just encountered this myself

**Comment by omonk** [comment]
regarding the docs here - https://chanfana.pages.dev/advanced-topics-patterns#nested-routers-organizing-complex-apis

If you copy and paste this code into a wrangler handler you get the following

```
⎔ Starting local server...
Error: ✘ [ERROR] service core:user:server: Uncaught TypeError: Cannot read properties of undefined (reading 'basePath')

    at null.<anonymous> (index.js:1664:25) in route
    at null.<anonymous> (index.js:11163:56)
    at null.<anonymous> (index.js:11230:9)

Error: ✘ [ERROR] The Workers runtime failed to start. There is likely additional logging output above.
```

Versions:

chanfana@2.8.1
hono@4.8.4
wrangler@4.24.0

I'm sure I'm doing something wrong, I can't be the only one having this issue!

**Comment by G4brym** [comment]
Hey @omonk thanks for pointing this out, the docs were wrong, i've just updated them to have a working example 😄 
Thanks for reporting, let me know if this fixed your issue
https://chanfana.pages.dev/advanced-topics-patterns#nested-routers-organizing-complex-apis

**Comment by omonk** [comment]
@G4brym you hero, thanks for that, working as expected now

**Comment by G4brym** [comment]
Nice, closing the issue as this is now fixed
